# -*- coding: utf-8 -*-
"""Index every Longform field definition from the manual PDF.

    python scripts/index_longform_fields.py

Each field in the Longform manual is introduced by a header block:

    區域淋巴結檢查數目
    Regional Lymph Nodes Examined
    欄位長度：2
    編碼範圍：00-90, 95-99
    癌登欄位序號 #2.14

This writes tcr_decoder/longform_fields.py -- the official field number, name,
width and legal-code range for every field the manual defines. Two uses:

  * it is the authority for 癌登欄位序號, so the data dictionary can be checked
    against the manual instead of against itself, and
  * it is the worklist for the fields that still have no code table.

The markdown conversion interleaves example tables with the header block, so
this reads the PDF, where the block stays together.
"""
import re
import sys
from pathlib import Path

try:
    import fitz  # PyMuPDF
except ImportError:  # pragma: no cover
    sys.exit('PyMuPDF is required: pip install pymupdf')

ROOT = Path(__file__).resolve().parent.parent
PDF = ROOT / 'docs' / 'Longform-Manual_Official-version_20251224_W-1.pdf'
OUT = ROOT / 'tcr_decoder' / 'longform_fields.py'

# Almost every field header uses '癌登欄位序號 #4.1.4.1'; exactly one uses a
# full-width colon instead of '#' (Minimally Invasive Surgery, p.182).
SEQ_RE = re.compile(r'癌登欄位序號\s*[#：:]?\s*([\d]+(?:\.[\d]+)*)')
WIDTH_RE = re.compile(r'^欄位長度：\s*(\d+)')
RANGE_RE = re.compile(r'^編碼範圍：\s*(.*)$')
# A continuation of the 編碼範圍 list: codes, ranges and separators only.
RANGE_CONT_RE = re.compile(r'^[0-9A-Za-z\-–,\s]+$')
STOP_RE = re.compile(r'^(癌登欄位序號|欄位長度|欄位敘述|收錄目的|編碼指引|NAACCR|編碼範圍)')


def page_lines(page):
    out = []
    for block in page.get_text('dict')['blocks']:
        for line in block.get('lines', []):
            t = ' '.join(''.join(s['text'] for s in line['spans']).split())
            if t:
                out.append(t)
    return out


def parse_page(lines, printed_page):
    """Every field header block on one page."""
    fields = []
    for i, line in enumerate(lines):
        m = SEQ_RE.search(line)
        if not m:
            continue
        seq = m.group(1).rstrip('.')

        # The block is the run of lines around the sequence number. Walk back
        # to the field name, which sits directly above 欄位長度.
        width = rng = ''
        name_zh = name_en = ''
        window = range(max(0, i - 12), min(len(lines), i + 12))
        anchor = None
        for k in window:
            if WIDTH_RE.match(lines[k]):
                anchor = k
                width = WIDTH_RE.match(lines[k]).group(1)
        for k in window:
            rm = RANGE_RE.match(lines[k])
            if rm:
                rng = rm.group(1).strip()
                for j in range(k + 1, min(len(lines), k + 6)):
                    if STOP_RE.match(lines[j]):
                        break
                    if RANGE_CONT_RE.match(lines[j]) and lines[j].strip():
                        rng = rng.rstrip(', ') + ', ' + lines[j].strip()
                    else:
                        break
        if anchor is not None:
            names = [lines[k] for k in range(max(0, anchor - 3), anchor)
                     if not re.fullmatch(r'\d+', lines[k])]
            if names:
                name_en = names[-1]
                name_zh = names[-2] if len(names) > 1 else ''
                if not re.search(r'[A-Za-z]', name_en) and name_zh:
                    name_zh, name_en = name_en, ''
        fields.append({
            'seq': seq, 'page': printed_page, 'width': int(width) if width else 0,
            'name_zh': name_zh, 'name_en': name_en,
            'range': ' '.join(rng.replace(',,', ',').split()),
        })
    return fields


def main():
    doc = fitz.open(PDF)
    seen, fields = set(), []
    for idx in range(doc.page_count):
        for f in parse_page(page_lines(doc[idx]), idx - 8):
            if f['seq'] in seen:
                continue
            seen.add(f['seq'])
            fields.append(f)

    def key(f):
        return [int(p) for p in f['seq'].split('.')]

    fields.sort(key=key)
    coded = [f for f in fields if f['range']]
    print(f'{len(fields)} field definitions, {len(coded)} with an official '
          f'編碼範圍')

    L = ['# -*- coding: utf-8 -*-',
         '"""Official Longform field definitions, extracted from the manual.',
         '',
         'GENERATED by scripts/index_longform_fields.py -- edit that, not this.',
         '',
         'This is the authority for 癌登欄位序號 (the field number a registrar',
         'sees on the official form) and for each field\'s 欄位長度 and',
         '編碼範圍. It lets the data dictionary be checked against the manual',
         'rather than against itself, and it is the worklist for the fields',
         'that still have no code table in this package.',
         '"""',
         '',
         'from typing import Dict, NamedTuple',
         '',
         '',
         'class LongformField(NamedTuple):',
         '    seq: str          # 癌登欄位序號, e.g. "2.14"',
         '    name_zh: str',
         '    name_en: str',
         '    width: int        # 欄位長度 in characters, 0 if not stated',
         '    code_range: str   # 編碼範圍 as printed, "" if the field has none',
         '    page: int         # printed page in the Longform manual',
         '',
         '',
         'LONGFORM_FIELDS: Dict[str, LongformField] = {']
    for f in fields:
        L.append(f'    {f["seq"]!r}: LongformField('
                 f'{f["seq"]!r}, {f["name_zh"]!r}, {f["name_en"]!r}, '
                 f'{f["width"]}, {f["range"]!r}, {f["page"]}),')
    L += ['}',
          '',
          '',
          'def field_number(seq: str) -> LongformField:',
          '    """Official definition of one field, by its 癌登欄位序號."""',
          '    return LONGFORM_FIELDS[seq]',
          '',
          '',
          'CODED_FIELDS = tuple(f.seq for f in LONGFORM_FIELDS.values()',
          '                     if f.code_range)',
          '']
    OUT.write_text('\n'.join(L), encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)} ({len(L)} lines)')


if __name__ == '__main__':
    main()
