# -*- coding: utf-8 -*-
"""Official Longform field definitions, extracted from the manual.

GENERATED by scripts/index_longform_fields.py -- edit that, not this.

This is the authority for 癌登欄位序號 (the field number a registrar
sees on the official form) and for each field's 欄位長度 and
編碼範圍. It lets the data dictionary be checked against the manual
rather than against itself, and it is the worklist for the fields
that still have no code table in this package.
"""

from typing import Dict, NamedTuple


class LongformField(NamedTuple):
    seq: str          # 癌登欄位序號, e.g. "2.14"
    name_zh: str
    name_en: str
    width: int        # 欄位長度 in characters, 0 if not stated
    code_range: str   # 編碼範圍 as printed, "" if the field has none
    page: int         # printed page in the Longform manual


LONGFORM_FIELDS: Dict[str, LongformField] = {
    '1.1': LongformField('1.1', '申報醫院代碼', 'Reporting Hospital Code', 10, '', 52),
    '1.2': LongformField('1.2', '病歷號碼', 'Medical Record Number', 10, '', 53),
    '1.3': LongformField('1.3', '姓名', 'Name', 200, '', 54),
    '1.4': LongformField('1.4', '身分證統一編號', 'ID Number', 10, '', 55),
    '1.5': LongformField('1.5', '性別', 'Sex', 1, '1-4, 9', 56),
    '1.6': LongformField('1.6', '出生日期', 'Date of Birth', 8, '', 57),
    '1.7': LongformField('1.7', '戶籍地代碼', 'Residence Code', 4, '', 59),
    '2.1': LongformField('2.1', '診斷年齡', 'Age at Diagnosis', 3, '000-120, 999', 62),
    '2.2': LongformField('2.2', '癌症發生順序號碼', 'Sequence Number', 2, '01-99', 63),
    '2.3': LongformField('2.3', '個案分類', 'Class of Case', 1, '0-3, 5, 7-9', 64),
    '2.3.1': LongformField('2.3.1', '診斷狀態分類', 'Class of Diagnosis Status', 1, '1-3, 5, 7-8', 73),
    '2.3.2': LongformField('2.3.2', '治療狀態分類', 'Class of Treatment Status', 1, '0-9', 74),
    '2.4': LongformField('2.4', '首次就診日期', 'Date of First Contact', 8, '', 77),
    '2.5': LongformField('2.5', '最初診斷日期', 'Date of Initial Diagnosis', 8, '', 78),
    '2.6': LongformField('2.6', '原發部位', 'Primary Site', 5, 'C000-C809', 81),
    '2.7': LongformField('2.7', '側性', 'Laterality', 1, '0-5, 9', 87),
    '2.8': LongformField('2.8', '組織型態', 'Histology', 5, '', 89),
    '2.9': LongformField('2.9', '性態碼', 'Behavior Code', 1, '2, 3', 91),
    '2.10.1': LongformField('2.10.1', '臨床分級/分化', 'Grade/Differentiation Clinical', 1, '1-5, 8-9, A-E, H, L-M, S, X', 93),
    '2.10.2': LongformField('2.10.2', '病理分級/分化', 'Grade/Differentiation Pathological', 1, '1-5, 8-9, A-E, H, L-M, S, X', 97),
    '2.11': LongformField('2.11', '癌症確診方式', 'Diagnostic Confirmation', 1, '1-9', 101),
    '2.12': LongformField('2.12', '首次顯微鏡檢證實日期', 'Date of First Microscopic Confirmation', 8, '', 105),
    '2.13': LongformField('2.13', '腫瘤大小', 'Tumor Size', 3, '000-990, 998, 999', 108),
    '2.13.1': LongformField('2.13.1', '神經侵襲', 'Perineural Invasion', 1, '0,1,7-9', 114),
    '2.13.2': LongformField('2.13.2', '淋巴管或血管侵犯', 'Lymph vessels or Vascular Invasion (LVI)', 1, '0,1,7-9', 116),
    '2.14': LongformField('2.14', '區域淋巴結檢查數目', 'Regional Lymph Nodes Examined', 2, '00-90, 95-99', 118),
    '2.15': LongformField('2.15', '區域淋巴結侵犯數目', 'Regional Lymph Nodes Positive', 2, '00-90, 95, 97-99', 121),
    '3.1': LongformField('3.1', '診斷性及分期性手術處置日期', 'Date of Surgical Diagnostic and Staging Procedure', 8, '', 126),
    '3.2': LongformField('3.2', 'Surgical Diagnostic and Staging Procedure at', 'Other Facility', 2, '00-07, 09-14', 128),
    '3.3': LongformField('3.3', 'Surgical Diagnostic and Staging Procedure', 'at This Facility', 2, '00-07, 09-14', 133),
    '3.4': LongformField('3.4', '臨床T', 'Clinical T', 4, '', 136),
    '3.5': LongformField('3.5', '臨床N', 'Clinical N', 3, '', 138),
    '3.6': LongformField('3.6', '臨床M', 'Clinical M', 3, '', 140),
    '3.7': LongformField('3.7', '臨床期別組合', 'Clinical Stage Group', 3, '', 142),
    '3.8': LongformField('3.8', '臨床分期字根/字首', 'Clinical Stage (Prefix/Suffix) Descriptor', 1, '0, 3, 9', 144),
    '3.10': LongformField('3.10', '病理T', 'Pathologic T', 4, '', 145),
    '3.11': LongformField('3.11', '病理N', 'Pathologic N', 3, '', 147),
    '3.12': LongformField('3.12', '病理M', 'Pathologic M', 3, '', 149),
    '3.13': LongformField('3.13', '病理期別組合', 'Pathologic Stage Group', 3, '', 152),
    '3.14': LongformField('3.14', '病理分期字根/字首', 'Pathologic Stage (Prefix/Suffix) Descriptor', 1, '0, 3-4, 6, 9', 154),
    '3.16': LongformField('3.16', 'AJCC 癌症分期版本與章節', 'The Edition and Chapter of AJCC Cancer Staging', 5, '', 155),
    '3.17': LongformField('3.17', '其他分期系統', 'Other Staging System', 2, '00-02, 06-07, 09, 11-13, 20-22', 157),
    '3.19': LongformField('3.19', '其他分期系統期別(臨床)', 'Clinical Other Staging Group', 4, '', 159),
    '3.21': LongformField('3.21', '其他分期系統期別(病理)', 'Pathologic Other Staging Group', 4, '', 164),
    '4.1': LongformField('4.1', '首次療程開始日期', 'Date of First Course of Treatment', 8, '', 170),
    '4.1.1': LongformField('4.1.1', '首次手術日期', 'Date of First Surgical Procedure', 8, '', 173),
    '4.1.2': LongformField('4.1.2', 'Date of Most Definite Surgical Resection of the Primary', 'Site', 8, '', 175),
    '4.1.3': LongformField('4.1.3', 'Surgical Procedure of Primary Site', 'at Other Facility', 3, '000, 100-800, 900, 980, 990', 177),
    '4.1.4': LongformField('4.1.4', 'Surgical Procedure of Primary Site', 'at This Facility', 3, '000, 100-800, 900, 980, 990', 179),
    '4.1.5': LongformField('4.1.5', '原發部位手術邊緣', 'Surgical Margins of the Primary Site', 1, '0-5, 7-9, A-F', 184),
    '4.1.5.1': LongformField('4.1.5.1', '原發部位手術切緣距離', 'Surgical Margins Distance of the Primary Site', 3, '000-980, 987, 988, 990-991, 999, A01-A09', 188),
    '4.1.6': LongformField('4.1.6', 'Scope of Regional Lymph Node Surgery', 'at Other Facility', 1, '0-7, 9', 194),
    '4.1.7': LongformField('4.1.7', 'Scope of Regional Lymph Node Surgery', 'at This Facility', 1, '0-7, 9', 198),
    '4.1.8': LongformField('4.1.8', 'Surgical Procedure/Other Site', 'at Other Facility', 1, '0-5, 9', 201),
    '4.1.9': LongformField('4.1.9', 'Surgical Procedure/Other Site', 'at This Facility', 1, '0-5, 9', 203),
    '4.1.10': LongformField('4.1.10', '原發部位未手術原因', 'Reason for No Surgery of Primary Site', 1, '0-3, 5-9', 205),
    '4.2.1.1': LongformField('4.2.1.1', '放射治療臨床標靶體積摘要', 'RT Target Summary', 2, '-9, -1, 0-63', 207),
    '4.2.1.2': LongformField('4.2.1.2', '放射治療儀器', 'RT Modality', 3, '-9, -1, 0-127', 212),
    '4.2.1.3': LongformField('4.2.1.3', '放射治療開始日期', 'Date of RT Started', 8, '', 216),
    '4.2.1.4': LongformField('4.2.1.4', '放射治療結束日期', 'Date of RT Ended', 8, '', 218),
    '4.2.1.5': LongformField('4.2.1.5', '放射治療與手術順序', 'Sequence of Radiotherapy and Surgery', 2, '-9, -8, -7, -6, -1, 0-7', 220),
    '4.2.1.6': LongformField('4.2.1.6', 'Sequence of Locoregional Therapy and Systemic', 'Therapy', 2, '-9, -8, -7, -1, 0-7', 224),
    '4.2.1.8': LongformField('4.2.1.8', '放射治療執行狀態', 'RT Status', 2, '00-10, 99', 228),
    '4.2.2.1': LongformField('4.2.2.1', '體外放射治療技術', 'EBRT Technique', 3, '-9, -1, 0-111', 230),
    '4.2.2.2.1': LongformField('4.2.2.2.1', '最高放射劑量臨床標靶體積', 'Target of CTV_H', 2, '-9, -1, 0-63', 234),
    '4.2.2.2.2': LongformField('4.2.2.2.2', '最高放射劑量臨床標靶體積劑量', 'Dose to CTV_H (cGy)', 5, '00000-99999', 238),
    '4.2.2.2.3': LongformField('4.2.2.2.3', '最高放射劑量臨床標靶體積治療次數', 'Number of Fractions to CTV_H', 2, '00-99', 240),
    '4.2.2.3.1': LongformField('4.2.2.3.1', '較低放射劑量臨床標靶體積', 'Target of CTV_L', 2, '-9, -1, 0-63', 242),
    '4.2.2.3.2': LongformField('4.2.2.3.2', '較低放射劑量臨床標靶體積劑量', 'Dose to CTV_L (cGy)', 5, '00000-99999', 245),
    '4.2.2.3.3': LongformField('4.2.2.3.3', '較低放射劑量臨床標靶體積治療次數', 'Number of Fractions to CTV_L', 2, '00-99', 247),
    '4.2.3.1': LongformField('4.2.3.1', '其他放射治療儀器', 'Other RT Modality', 2, '-9, -1, 0, 2, 4, 8, 16, 32, 64', 249),
    '4.2.3.2': LongformField('4.2.3.2', '其他放射治療技術', 'Other RT Technique', 2, '-9, -1, 0-7, 9-10, 12, 17-18, 20, 33-34, 36, 65-66, 68, 97-99', 254),
    '4.2.3.3.1': LongformField('4.2.3.3.1', '其他放射治療臨床標靶體積', 'Target of Other RT', 2, '-9, -1, 0-63', 258),
    '4.2.3.3.2': LongformField('4.2.3.3.2', '其他放射治療臨床標靶體積劑量', 'Dose to Target of Other RT', 5, '00000-99999', 261),
    '4.2.3.3.3': LongformField('4.2.3.3.3', '其他放射治療臨床標靶體積治療次數', 'Number of Fractions of Other RT', 2, '00-99', 263),
    '4.3.1': LongformField('4.3.1', '全身性治療開始日期', 'Date of Systemic Therapy Started', 8, '', 265),
    '4.3.2': LongformField('4.3.2', '外院化學治療', 'Chemotherapy at Other Facility', 2, '00-13, 20-21, 30-31, 99', 267),
    '4.3.3': LongformField('4.3.3', '申報醫院化學治療', 'Chemotherapy at This Facility', 2, '00-13, 20-21, 30-31, 81-83, 85-88, 99', 270),
    '4.3.4': LongformField('4.3.4', '申報醫院化學治療開始日期', 'Date of Chemotherapy Started at this Facility', 8, '', 274),
    '4.3.5': LongformField('4.3.5', '外院荷爾蒙/類固醇治療', 'Hormone/Steroid Therapy at Other Facility', 2, '00-03, 20-21, 30-31, 99', 276),
    '4.3.6': LongformField('4.3.6', '申報醫院荷爾蒙/類固醇治療', 'Hormone/Steroid Therapy at This Facility', 2, '00-03, 20-21, 30-31, 82-83, 85-88, 99', 278),
    '4.3.7': LongformField('4.3.7', 'Date of Hormone/Steroid Therapy Started', 'at This Facility', 8, '', 281),
    '4.3.8': LongformField('4.3.8', '外院免疫治療', 'Immunotherapy at Other Facility', 2, '00-07, 20-23, 30-33, 40-41,99', 282),
    '4.3.9': LongformField('4.3.9', '申報醫院免疫治療', 'Immunotherapy at This Facility', 2, '00-07, 20-23, 30-33, 40-41,82-83,85-88, 99', 284),
    '4.3.10': LongformField('4.3.10', '申報醫院免疫治療開始日期', 'Date of Immunotherapy Started at This Facility', 8, '', 287),
    '4.3.11': LongformField('4.3.11', '骨髓/幹細胞移植或內分泌處置', 'Hematologic Transplant and Endocrine Procedure', 2, '00, 10-12, 20-22, 25, 30, 40, 50, 82-83, 85-88, 99', 288),
    '4.3.12': LongformField('4.3.12', 'Date of Hematologic Transplant and Endocrine', 'Procedures Started at This Facility', 8, '', 291),
    '4.3.13': LongformField('4.3.13', '外院標靶治療', 'Targeted therapy at Other Facility', 2, '00-01, 20-21, 30-31, 99', 292),
    '4.3.14': LongformField('4.3.14', '申報醫院標靶治療', 'Targeted therapy at This Facility', 2, '00-01, 20-21, 30-31, 82-83, 85-88, 99', 294),
    '4.3.15': LongformField('4.3.15', '申報醫院標靶治療開始日期', 'Date of Targeted therapy Started at This Facility', 8, '', 297),
    '4.4': LongformField('4.4', '申報醫院緩和照護', 'Palliative Care at This Facility', 1, '0-7, 9', 298),
    '4.5.1': LongformField('4.5.1', '其他治療', 'Other Treatment', 2, '00-03, 99', 301),
    '4.5.2': LongformField('4.5.2', '其他治療開始日期', 'Date of Other Treatment Started', 8, '', 303),
    '4.16': LongformField('4.16', '', '', 0, '', 358),
    '5.1': LongformField('5.1', '首次復發或癌症狀態追蹤日期', 'Date of First Recurrence or Cancer Status Follow-Up', 8, '', 306),
    '5.2': LongformField('5.2', '首次復發型式', 'Type of First Recurrence', 2, '00, 04,06, 10, 13-17, 20-22, 25-, 27, 30, 36, 40, 46, 51-60, 62, 70, 88, 99', 308),
    '5.3': LongformField('5.3', '最後聯絡或死亡日期', 'Date of Last Contact or Death', 8, '', 312),
    '5.4': LongformField('5.4', '生存狀態', 'Vital Status', 1, '0-1', 313),
    '6.1': LongformField('6.1', '摘錄者', 'Abstracted by', 10, '', 316),
    '7.1': LongformField('7.1', '身高', 'Height', 3, '000-999', 320),
    '7.2': LongformField('7.2', '體重', 'Weight', 3, '000-999', 321),
    '7.3': LongformField('7.3', '吸菸行為', 'Smoking Behavior', 6, '', 322),
    '7.4': LongformField('7.4', '嚼檳榔行為', 'Betel Nut Chewing Behavior', 6, '', 324),
    '7.5': LongformField('7.5', '喝酒行為', 'Drinking Behavior', 3, '000-004, 009, 999', 326),
    '7.6': LongformField('7.6', '首次治療前生活功能狀態評估', 'Assessment of Performance Status before Treatment', 3, '000-005, 100, 104, 204, 209, 303-304, 309, 403, 409, 502- 503, 509, 602, 609, 701-702, 709, 801, 809, 900-901, 909, 988, 999', 327),
    '7.7': LongformField('7.7', '同癌家族病史', 'Family History of Same Cancer', 6, '', 330),
    '7.8': LongformField('7.8', '其他因子8-10', 'Other Factor 8-10', 3, '988', 333),
    '8.1': LongformField('8.1', '癌症部位特定因子1-20', 'Site-Specific Factor 1-20', 3, '000-999', 336),
    '8.4': LongformField('8.4', '', '', 0, '', 352),
}


def field_number(seq: str) -> LongformField:
    """Official definition of one field, by its 癌登欄位序號."""
    return LONGFORM_FIELDS[seq]


CODED_FIELDS = tuple(f.seq for f in LONGFORM_FIELDS.values()
                     if f.code_range)
